version: '3'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: covid_db
    ports:
      - 5432:5432
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db_cron
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=covid_db
    ports:
      - 8080:8080
  db_cron:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    depends_on: 
      - db

